name: Tests

on:
  pull_request:
    branches:
      - master
      - feature
  push:
    branches:
      - master
      - feature

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Copy .env file
        run: |
          cp .env.ci .env

      - name: Run composer
        run: |
          composer install --no-interaction

      - name: Run test suite
        run: |
          vendor/bin/phpunit
